version: "2"

services:
  app:
    build: .
    command: python tests.py
    ports:
    - "8000:8000"
    volumes:
    - ./:/var/www/epsg.io
    environment:
      FLASK_DEBUG: "1"
      FLASK_ENV: "development"
